"""create table input_output

Revision ID: bb7bfb6b4ed5
Revises: 
Create Date: 2025-03-21 14:59:06.511820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7bfb6b4ed5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('jawaban', sa.Text(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('input_output')
    # ### end Alembic commands ###
