"""Re-initialize migrations

Revision ID: fe7a74d30d5f
Revises: 
Create Date: 2025-03-29 20:49:46.524878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7a74d30d5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('input_output', schema=None) as batch_op:
        batch_op.drop_column('kesimpulan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('input_output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kesimpulan_id', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
